/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-geist)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-instrument)', 'Georgia', 'serif'],
        mono: ['var(--font-jetbrains)', 'monospace'],
      },
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-elevated': 'var(--surface-elevated)',
        'surface-glass': 'var(--surface-glass)',
        border: 'var(--border)',
        primary: 'var(--primary)',
        'primary-dark': 'var(--primary-dark)',
        'primary-light': 'var(--primary-light)',
        accent: 'var(--accent)',
        'accent-dark': 'var(--accent-dark)',
        'primary-text': 'var(--primary-text)',
        'secondary-text': 'var(--secondary-text)',
        'muted-text': 'var(--muted-text)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        info: 'var(--info)',
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '1.4', letterSpacing: '0.01em' }],
        xs:    ['12px', { lineHeight: '1.4' }],
        sm:    ['13px', { lineHeight: '1.55' }],
        base:  ['16px', { lineHeight: '1.60' }],
        lg:    ['18px', { lineHeight: '1.65' }],
        xl:    ['20px', { lineHeight: '1.25' }],
        '2xl': ['24px', { lineHeight: '1.20' }],
        '3xl': ['32px', { lineHeight: '1.15', letterSpacing: '-0.015em' }],
        '4xl': ['42px', { lineHeight: '1.10', letterSpacing: '-0.02em' }],
        '5xl': ['48px', { lineHeight: '1.08', letterSpacing: '-0.025em' }],
        '6xl': ['72px', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
      },
      fontWeight: {
        300: '300',
        400: '400',
        500: '500',
        600: '600',
        700: '700',
        800: '800',
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '10px',
        md: '10px',
        lg: '14px',
        xl: '18px',
        '2xl': '24px',
      },
      boxShadow: {
        xs:     '0 1px 3px rgba(0,0,0,0.05)',
        soft:   '0 2px 8px rgba(0,0,0,0.08)',
        card:   '0 2px 6px rgba(0,0,0,0.25), 0 20px 60px rgba(0,0,0,0.30), 0 60px 120px rgba(0,0,0,0.20)',
        lg:     '0 8px 40px rgba(23,76,60,0.12)',
        cta:    '0 2px 6px rgba(0,0,0,0.15), 0 10px 30px rgba(23,76,60,0.25)',
        'focus-green': '0 0 0 3px rgba(23,76,60,0.20)',
        'focus-gold':  '0 0 0 3px rgba(200,169,107,0.30)',
        'primary-glow': '0 0 16px rgba(23,76,60,0.30)',
      },
      animation: {
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'pulse-subtle': 'pulse-subtle 2s ease-in-out infinite',
        'spin-slow': 'spin 1.5s linear infinite',
        'bounce-in': 'bounce-in 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-up': 'slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-in': 'fade-in 0.3s ease-out',
        'warp': 'warp var(--warp-duration, 3s) linear infinite var(--warp-delay, 0s)',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.5' },
        },
        'bounce-in': {
          '0%':   { opacity: '0', transform: 'scale(0.85)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-up': {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'warp': {
          '0%': { transform: 'translate3d(100vw, -100vh, 0)', opacity: '0' },
          '20%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { transform: 'translate3d(-100vw, 100vh, 0)', opacity: '0' },
        }
      },
      spacing: {
        '4.5': '18px',
        '13': '52px',
        '15': '60px',
        '18': '72px',
        '22': '88px',
      },
      transitionTimingFunction: {
        'cinematic': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};
